"""empty message

Revision ID: 753a9865defc
Revises: 
Create Date: 2018-05-04 16:43:52.383898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753a9865defc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('surname', sa.String(length=150), nullable=False),
    sa.Column('city_of_interest', sa.String(length=150), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bien_immobilier',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('type_prop', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('car_rooms', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['utilisateurs.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bien_immobilier')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
